builds:
  - main: ./cmd/sindri
    id: sindri
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/ladon
    id: ladon
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.sindri.Dockerfile
    image_templates:
      - ghcr.io/frantjc/sindri:{{ .RawVersion }}
      - ghcr.io/frantjc/sindri:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/sindri:{{ .Major }}
      - ghcr.io/frantjc/sindri:latest
  - dockerfile: goreleaser.ladon.Dockerfile
    image_templates:
      - ghcr.io/frantjc/ladon:{{ .RawVersion }}
      - ghcr.io/frantjc/ladon:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/ladon:{{ .Major }}
      - ghcr.io/frantjc/ladon:latest
