version: 2
builds:
  - main: ./cmd/boil
    id: boil
    binary: boil
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/boiler
    id: boiler
    binary: boiler
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/mist
    id: mist
    binary: mist
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/valheimw
    id: valheimw
    binary: valheimw
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.boiler.Dockerfile
    image_templates:
      - ghcr.io/frantjc/boiler:{{ .RawVersion }}
      - ghcr.io/frantjc/boiler:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/boiler:{{ .Major }}
      - ghcr.io/frantjc/boiler:latest
  - dockerfile: goreleaser.mist.Dockerfile
    image_templates:
      - ghcr.io/frantjc/mist:{{ .RawVersion }}
      - ghcr.io/frantjc/mist:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/mist:{{ .Major }}
      - ghcr.io/frantjc/mist:latest
  - dockerfile: goreleaser.valheimw.Dockerfile
    image_templates:
      - ghcr.io/frantjc/valheimw:{{ .RawVersion }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}
      - ghcr.io/frantjc/valheimw:latest
brews:
  - repository:
      owner: frantjc
      name: homebrew-tap
    name: boil
    ids:
      - boil
    directory: Formula
    skip_upload: auto
    homepage:  https://github.com/frantjc/sindri
    license: MIT
    test: |
      system "#{bin}/boil --version"
  - repository:
      owner: frantjc
      name: homebrew-tap
    name: valheimw
    ids:
      - valheimw
    directory: Formula
    skip_upload: auto
    homepage:  https://github.com/frantjc/sindri
    license: MIT
    test: |
      system "#{bin}/valheimw --version"
