builds:
  - main: ./cmd/sindri
    id: sindri
    binary: sindri
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/valheimw
    id: valheimw
    binary: valheimw
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/boil
    id: boil
    binary: boil
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.boil.Dockerfile
    image_templates:
      - ghcr.io/frantjc/boil:{{ .RawVersion }}
      - ghcr.io/frantjc/boil:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/boil:{{ .Major }}
      - ghcr.io/frantjc/boil:latest
  - dockerfile: goreleaser.valheimw.Dockerfile
    image_templates:
      - ghcr.io/frantjc/valheimw:{{ .RawVersion }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}
      - ghcr.io/frantjc/valheimw:latest
