builds:
  - main: ./cmd/sindri
    id: sindri
    binary: sindri
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/valheimw
    id: valheimw
    binary: valheimw
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/boil
    id: boil
    binary: boil
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/mist
    id: mist
    binary: mist
    ldflags:
      - -s -w -X github.com/frantjc/sindri.VersionCore={{ .RawVersion }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
# TODO: ...
# dockers:
#   - dockerfile: goreleaser.Dockerfile
#     image_templates:
#       - ghcr.io/frantjc/sindri:{{ .RawVersion }}
#       - ghcr.io/frantjc/sindri:{{ .Major }}.{{ .Minor }}
#       - ghcr.io/frantjc/sindri:{{ .Major }}
#       - ghcr.io/frantjc/sindri:latest
