version: 2
builds:
  - main: ./cmd/boiler
    id: boiler
    binary: boiler
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/mist
    id: mist
    binary: mist
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
  - main: ./cmd/valheimw
    id: valheimw
    binary: valheimw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
release:
  skip_upload: true
dockers:
  - dockerfile: goreleaser.boiler.Dockerfile
    image_templates:
      - ghcr.io/frantjc/boiler:{{ .RawVersion }}
      - ghcr.io/frantjc/boiler:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/boiler:{{ .Major }}
      - ghcr.io/frantjc/boiler:latest
  - dockerfile: goreleaser.mist.Dockerfile
    image_templates:
      - ghcr.io/frantjc/mist:{{ .RawVersion }}
      - ghcr.io/frantjc/mist:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/mist:{{ .Major }}
      - ghcr.io/frantjc/mist:latest
  - dockerfile: goreleaser.valheimw.Dockerfile
    image_templates:
      - ghcr.io/frantjc/valheimw:{{ .RawVersion }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}
      - ghcr.io/frantjc/valheimw:latest
