version: 2
builds:
  - main: ./cmd/mist
    id: mist
    binary: mist
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
  - main: ./cmd/valheimw
    id: valheimw
    binary: valheimw
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
upx:
  - enabled: true
checksum:
  name_template: checksums.txt
source:
  enabled: true
sboms:
  - artifacts: source
release:
  prerelease: auto
  skip_upload: true
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - dockerfile: goreleaser.mist.Dockerfile
    image_templates:
      - ghcr.io/frantjc/mist:{{ .RawVersion }}
      - ghcr.io/frantjc/mist:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/mist:{{ .Major }}
      - ghcr.io/frantjc/mist:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --platform=linux/amd64
  - dockerfile: goreleaser.valheimw.Dockerfile
    image_templates:
      - ghcr.io/frantjc/valheimw:{{ .RawVersion }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}.{{ .Minor }}
      - ghcr.io/frantjc/valheimw:{{ .Major }}
      - ghcr.io/frantjc/valheimw:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --platform=linux/amd64
docker_signs:
  - cmd: cosign
    artifacts: images
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
    output: true
