services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - -vv
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn/2.23.2
    volumes:
      - ./dev/cache:/root/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
