services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - -VV
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn/2.23.2
    volumes:
      - ./cache:/root/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  buildkitd:
    image: moby/buildkit
    privileged: true
    ports:
      - 1234:1234
    command:
      - --debug
      - --addr
      - tcp://0.0.0.0:1234
  stoker:
    build:
      context: .
      args:
        tool: stoker
    command:
      - -VV
      - --path=/api/v1
      - --webhook-secure=false
      - --buildkitd=tcp://buildkitd:1234
      - node
      - /app/server.js
    volumes:
      - ./cache:/root/.cache
      - ~/.kube:/root/.kube
    ports:
      - 5050:5050
    depends_on:
      - buildkitd
  migrate:
    image: alpine
    volumes:
      - ./hack/migrate.sh:/usr/local/bin/migrate
    entrypoint: migrate http://stoker:5050
    depends_on:
      - stoker
  boiler:
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
      - --buildkitd=tcp://buildkitd:1234
      - --db=stokercr://
    volumes:
      - ./cache:/root/.cache
      - ~/.kube:/root/.kube
    ports:
      - 5000:5000
    depends_on:
      - buildkitd
      - stoker
  valheim:
    image: localhost:5000/896660
    command:
      - -name
      - My server
      - -world
      - Dedicated
      - -password
      - secret
      - -crossplay
    ports:
      - 2456:2456/udp
    depends_on:
      - boiler
