services:
  sindri:
    image: ghcr.io/frantjc/sindri:${TAG:-1.3.2}
    build:
      context: .
      dockerfile: sindri.Dockerfile
    ports:
      - 2456:2456/udp
      - 8080:8080
    volumes:
      - ./hack/var/lib/sindri:/var/lib/sindri
      - ./hack/run/sindri:/run/sindri
    command:
      - -VV
      # - --no-download
      # - --mods-only
      - --state=/run/sindri
      - --root=/var/lib/sindri
      - --mod=RandyKnapp/EquipmentAndQuickSlots
    environment:
      VALHEIM_PASSWORD: ${VALHEIM_PASSWORD:-atleast5chars}
  ladon:
    image: ghcr.io/frantjc/ladon:${TAG:-1.3.2}
    build:
      context: .
      dockerfile: ladon.Dockerfile
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    volumes:
      - ./hack/var/lib/ladon:/var/lib/ladon
      - ./hack/run/ladon:/run/ladon
    command:
      - -VV
      - --no-download
      - --state=/run/ladon
      - --root=/var/lib/ladon
