version: "3.4"

services:
  sindri:
    image: ghcr.io/frantjc/sindri:${TAG:-1.2.7}
    build: .
    ports:
      - 2456:2456/udp
      - 8080:8080
    volumes:
      - ./hack/var/lib/sindri:/var/lib/sindri
      - ./hack/run/sindri:/run/sindri
    command:
      - -VV
      # - --no-download
      # - --mods-only
      - --state=/run/sindri
      - --root=/var/lib/sindri
      - --mod=Nexus/FarmGrid
    environment:
      VALHEIM_PASSWORD: ${VALHEIM_PASSWORD:-atleast5chars}
