services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - --mod=RandyKnapp/EquipmentAndQuickSlots
    volumes:
      - ./hack:/home/valheimw/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  boiler:
    build:
      context: .
      args:
        tool: boiler
    volumes:
      - ./hack:/home/boiler/.cache
    ports:
      - 8080:8080
  xeyes:
    build:
      context: .
      dockerfile: xeyes.Dockerfile
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
