services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - -VV
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn/2.23.2
    volumes:
      - ./cache:/root/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  buildkitd:
    image: moby/buildkit
    privileged: true
    command:
      - --addr
      - tcp://0.0.0.0:1234
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sindri
      POSTGRES_USER: sindri
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sindri -d sindri"]
      interval: 3s
      retries: 3
      start_period: 10s
  stoker:
    build:
      context: .
      args:
        tool: stoker
    command:
      - -VV
      - --db=postgres://sindri:${POSTGRES_PASSWORD:-changeme}@postgres:5432/sindri?sslmode=disable
      - --path=/api/v1
      - node
      - /app/server.js
    volumes:
      - ./cache:/root/.cache
    ports:
      - 5050:5050
    depends_on:
      postgres:
        condition: service_healthy
  boiler:
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
      - --buildkitd=tcp://buildkitd:1234
      - --db=postgres://sindri:${POSTGRES_PASSWORD:-changeme}@postgres:5432/sindri?sslmode=disable
    volumes:
      - ./cache:/root/.cache
    ports:
      - 5000:5000
    depends_on:
      buildkitd:
        condition: service_started 
      postgres:
        condition: service_healthy
  valheim:
    image: localhost:5000/896660
    command:
      - -name
      - My server
      - -world
      - Dedicated
      - -password
      - secret
      - -crossplay
    ports:
      - 2456:2456/udp
    depends_on:
      - boiler
  migrate:
    image: alpine 
    container_name: migrate
    volumes:
      - ./migrate:/data
    entrypoint: ["/bin/sh", "-c", "/data/valheim.sh"]
    depends_on:
      - stoker