services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - -VV
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn/2.23.2
    volumes:
      - ./hack:/root/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  buildkitd:
    image: moby/buildkit
    privileged: true
    command:
      - --addr
      - tcp://0.0.0.0:1234
    networks:
      - postgres
  boiler:
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
      - --buildkitd=tcp://buildkitd:1234
      - --db=postgres://phish3y:pwd@postgres:5432/steamapp?sslmode=disable
    volumes:
      - ./hack:/root/.cache
    ports:
      - 5000:5000
    depends_on:
      - buildkitd
    networks:
      - postgres
  valheim:
    image: localhost:5000/896660
    command:
      - -name
      - My server
      - -world
      - Dedicated
      - -password
      - secret
      - -crossplay
    ports:
      - 2456:2456/udp
    depends_on:
      - boiler
networks:
  postgres:
    external: true