services:
  valheimw:
    image: ghcr.io/frantjc/valheimw
    build:
      context: .
      args:
        tool: valheimw
    command:
      - --mod=RandyKnapp/EquipmentAndQuickSlots
    volumes:
      - ./hack:/home/valheimw/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  buildkitd:
    image: moby/buildkit:rootless
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    command:
      - --addr
      - tcp://0.0.0.0:1234
      - --oci-worker-no-process-sandbox
  boiler:
    image: ghcr.io/frantjc/boiler
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
      - tcp://buildkitd:1234
    volumes:
      - ./hack:/home/boiler/.cache
    ports:
      - 5000:5000
    depends_on:
      - buildkitd
