services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - -VV
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn/2.23.2
    volumes:
      - ./hack:/root/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  buildkitd:
    image: moby/buildkit
    privileged: true
    command:
      - --addr
      - tcp://0.0.0.0:1234
  boiler:
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
      - --buildkitd=tcp://buildkitd:1234
    volumes:
      - ./hack:/root/.cache
    ports:
      - 5000:5000
    depends_on:
      - buildkitd
