services:
  valheim:
    image: ghcr.io/frantjc/valheim:${TAG:-2.0.0}
    build:
      context: .
      args:
        - TOOL=valheim
    command:
      - --mod=RandyKnapp/EquipmentAndQuickSlots
      - --wd=/root/.cache/sindri/valheim
    volumes:
      - ./hack:/root/.cache
    environment:
      VALHEIM_PASSWORD: valheim
