services:
  valheimw:
    image: ghcr.io/frantjc/valheimw
    build:
      context: .
      args:
        tool: valheimw
    command:
      - --mod=RandyKnapp/EquipmentAndQuickSlots
    volumes:
      - ./hack:/home/valheimw/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  boiler:
    image: ghcr.io/frantjc/boiler
    build:
      context: .
      args:
        tool: boiler
    command:
      - -VV
    volumes:
      - ./hack:/home/boiler/.cache
    ports:
      - 5000:5000
