services:
  valheimw:
    build:
      context: .
      args:
        tool: valheimw
    command:
      - --mod=RandyKnapp/EquipmentAndQuickSlots
    volumes:
      - ./hack:/valheimw/.cache
    environment:
      VALHEIM_PASSWORD: hellothere
    ports:
      - 2456:2456/udp
      - 8080:8080
  boil:
    build:
      context: .
      args:
        tool: boil
    volumes:
      - ./hack:/boil/.cache
    ports:
      - 8080:8080
