apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sindri.fullname" . }}
  labels:
    {{- include "sindri.labels" . | nindent 4 }}
data:
  valheimPassword: {{ required ".Values.valheim.password is required" .Values.valheim.password | b64enc }}
type: Opaque
