---
apiVersion: sindri.frantj.cc/v1alpha1
kind: Steamapp
metadata:
  name: 896660-public
  namespace: sindri-system
  annotations:
    sindri.frantj.cc/approved: "true"
spec:
  appID: 896660
  aptPackages:
    - ca-certificates
  baseImage: docker.io/library/debian@sha256:8810492a2dd16b7f59239c1e0cc1e56c1a1a5957d11f639776bd6798e795608b
  branch: public
  entrypoint:
    - /home/steam/valheim_server.x86_64
  execs:
    - rm -r /home/steam/docker /home/steam/docker_start_server.sh /home/steam/start_server_xterm.sh /home/steam/start_server.sh
    - ln -s /home/steam/linux64/steamclient.so /usr/lib/x86_64-linux-gnu/steamclient.so
  launchType: server
  platformType: linux
  ports:
    - port: 2456
      protocols:
        - UDP
