# Default tag is "latest" which gets mapped to the Steam app branch "public"
FROM localhost:5000/2394010
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        xdg-utils
