services:
  boiler:
    image: ghcr.io/frantjc/boiler
    build:
      context: ../..
      args:
        tool: boiler
    command:
      - -VV
    volumes:
      - ./hack:/home/boiler/.cache
    ports:
      - 5000:5000
  palworld:
    build: .
