name: Build Push Core Keeper
on: [workflow_dispatch]
permissions:
  contents: write
  packages: write
jobs:
  build-push-corekeeper:
    runs-on: ubuntu-latest
    services:
      boiler:
        image: ghcr.io/frantjc/boiler
        ports:
          - 5000:5000
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: https://github.com/${{ github.repository }}.git#${{ github.sha }}:corekeeper
          push: true
          tags: |
            ghcr.io/frantjc/corekeeper
            ghcr.io/frantjc/corekeeper:public
