name: Build Push Steamapp
on:
  workflow_dispatch:
    inputs:
      app-id:
        description: Steam app ID to build and push.
        required: true
      branch:
        description: Steamapp branch to build.
        required: true
        default: public
permissions:
  contents: write
  pull-requests: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: |
          go install ./cmd/boil
      - run: |
          boil \
            --base debian:stable-slim \
            --beta ${{ inputs.branch }} \
            --ref ghcr.io/frantjc/sindri/${{ inputs.app-id }}:${{ inputs.branch }} \
            ${{ inputs.app-id }} \
              | docker load
          docker push ghcr.io/frantjc/sindri/${{ inputs.app-id }}:${{ inputs.branch }}
