name: Release
on:
  push:
    tags:
      # Rough semantic version regexp to only create releases
      # on complete semantic versions e.g. v1.0.0, but not v1.
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_BUILDKIT: 1
      - name: Run git config
        run: |
          git config --global user.email "$GIT_USER"
          git config --global user.name "$GIT_USER"
        env:
          GIT_USER: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      - uses: azure/setup-helm@v3
      - uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
